# Generated by Django 4.2.1 on 2023-07-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_start_time', models.TimeField()),
                ('exam_end_time', models.TimeField()),
                ('exam_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'candidate_exam_details',
                'ordering': ('exam_date',),
            },
        ),
        migrations.CreateModel(
            name='CandidateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_gender', models.CharField(max_length=20)),
                ('candidate_email', models.CharField(max_length=100, unique=True)),
                ('contact_number', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'candidate_student_tabl',
                'ordering': ('candidate_name',),
            },
        ),
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=205)),
            ],
            options={
                'db_table': 'topic_content_tbl',
                'ordering': ('content_name',),
            },
        ),
        migrations.CreateModel(
            name='ContentQuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=205)),
                ('option_2', models.CharField(max_length=205)),
                ('option_3', models.CharField(max_length=205)),
                ('option_4', models.CharField(max_length=205)),
                ('currect_option', models.IntegerField()),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ExamApp.contentmodel')),
            ],
            options={
                'db_table': 'content_question_tbl',
                'ordering': ('question',),
            },
        ),
        migrations.CreateModel(
            name='DashboardModelMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashbord_discription', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Dashboard',
                'ordering': ('dashbord_discription',),
            },
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=205, unique=True)),
            ],
            options={
                'db_table': 'topic_tbl',
                'ordering': ('topic_name',),
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_option_number', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='ExamApp.candidateexammodel')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='ExamApp.contentquestionsmodel')),
            ],
            options={
                'db_table': 'exam_quesion_result',
                'ordering': ('question_id',),
            },
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='ExamApp.topicmodel'),
        ),
        migrations.AddField(
            model_name='candidateexammodel',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='ExamApp.candidatemodel'),
        ),
    ]
