# Generated by Django 4.2.1 on 2023-08-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbltutorials_Content',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TutorialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_topics', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_tutorials',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='candidateexammodel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='candidatemodel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='contentmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='contentquestionsmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='dashboardmodelmaster',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='examquestionmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='topicmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='candidateexammodel',
            name='exam_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateexammodel',
            name='exam_end_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateexammodel',
            name='exam_start_time',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='VedioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VedioModel', models.CharField(max_length=255)),
                ('vedio_caption', models.CharField(max_length=255)),
                ('tutorial_content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vedio', to='ExamApp.tutorialcontentmodel')),
            ],
            options={
                'db_table': 'vedios',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TutorialsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_headings', models.CharField(max_length=255)),
                ('tutorial_data', models.CharField(max_length=255)),
                ('tutorial_content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorialdata', to='ExamApp.tutorialcontentmodel')),
            ],
            options={
                'db_table': 'tutorialdata_tbl',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='tutorialcontentmodel',
            name='tutorial_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorialsContent', to='ExamApp.tutorialmodel'),
        ),
    ]
